on:
  pull_request:
    branches:    
      - main

jobs:
  apply-label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.addLabels({
              labels: ['issue-status: needs-triage']
            })

