---
name: Create branch

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create branch
        id: create_branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          touch tests
          git add tests
          git checkout -b new-branch
          git commit -m "test"
          git push origin new-branch
          gh pr create --title "test" --fill
