---
name: Trigger release and bump version

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - closed

jobs:
  trigger-release-process:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check head commit message
        id: check_head_commit_message
        continue-on-error: true
        run: |
          git ss
          if [ $? -eq 1 ]
          then
            echo "valid_release_message=False" >> $GITHUB_OUTPUT
          else
            echo "valid_release_message=True" >> $GITHUB_OUTPUT
          fi

      - name: Skip
        if: ${{ steps.check_head_commit_message.outputs.validate_release_commit == 'True' }}
        run: |
          echo no sip
