---
name: test-docker

on:
  workflow_dispatch:
    inputs:
      git_rev:
        description: 'The git revision to deploy'
        required: true
        default: ''

jobs:
  test-docker:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Test change work directory
      working-directory: test_package
      run: |
          pwd
          python test.py

    - name: Test docker command
      run: |
          pwd
          docker

    - name: echo input
      run: |
          echo ${{ secrets[github.event.inputs.git_rev] }}
          echo ${{ github.event.inputs.git_rev }}
