---
name: Trigger release and bump version

on: workflow_dispatch

jobs:
  test:
    steps:
      - name: Check out
        uses: actions/checkout@v3
        # with:
          # token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push tag for triggering release
        run: |
          git tag test
          git push origin test

      - name: Bump version for new development
        run: |
          touch test
          git add .
          git push origin main
