---
name: echo github context

on:
  pull_request:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Echo context
        run: |

          echo ${{ github.event }}
          echo ${{ github.event_name }}
          echo ${{ github.event.pull_request }}
          echo ${{ github.event.pull_request.head }}
          echo ${{ github.event.pull_request.head.repo }}
          echo ${{ github.event.pull_request.head.repo.fork }}
