---
name: test-docker

on:
  workflow_dispatch:
    inputs:
      git_rev:
        description: 'The git revision to deploy'
        required: false
        default: ''

jobs:
  job-1:
    runs-on: 'ubuntu-20.04'
    if: ${{ input.git_rev == '' }}
    steps:
    - name: step 1
      id: step-1
      run: |
        echo "git_rev=from-first-step" >> $GITHUB_OUTPUT

  job-2:
    needs: job-1
    runs-on: 'ubuntu-20.04'
    if: |
      always() &&
      needs.job-1.result == "success"
    steps:
    - name: step 1
      id: step-1
      run: |
        echo ${{ input.git_rev if input.git_rev != '' else needs.job-1.git_rev}}