---
name: test-docker

on:
  workflow_dispatch:
    # inputs:
    #   git_rev:
    #     description: 'The git revision to deploy'
    #     required: true
    #     default: ''

jobs:
  test-docker:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v3

    - name: Test change work directory
      run: |
          git branch
