---
name: test-docker

on:
  workflow_dispatch:
    inputs:
      git_rev:
        description: 'The git revision to deploy'
        required: false
        default: ''

jobs:
  job-1:
    runs-on: 'ubuntu-20.04'
    if: ${{ inputs.git_rev == '' }}
    steps:
    - name: step 1
      id: step-1
      run: |
        echo "git_rev=from-first-step" >> $GITHUB_OUTPUT
    outputs:
      git_rev: ${{ steps.step-1.outputs.git_rev }}

  job-2:
    needs: job-1
    runs-on: 'ubuntu-20.04'
    if: |
      always()
    steps:
    - name: step 1
      id: step-1
      run: |
        if [ "$git_rev" == "" ]; then
          echo "git_rev=${{ needs.job-1.outputs.git_rev }}" >> $GITHUB_OUTPUT
        else
          echo "git_rev=${{ inputs.git_rev }}" >> $GITHUB_OUTPUT
        fi
    outputs:
      git_rev: ${{ steps.step-1.outputs.git_rev }}

  job-3:
    needs: job-2
    runs-on: 'ubuntu-20.04'
    if: always()
    steps:
      - name: step 1
        run: |
          echo ${{ needs.job-2.outputs.git_rev }}
          echo ${{ needs.job-2.outputs }}
          echo ${{ needs.job-2 }}